name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build & Deploy to custom branch
        uses: DavidS/jekyll-deploy@
        with:
          source-dir: docs
        env:
          JEKYLL_ENV: production
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
      # - name: Jekyll Build
      #   uses: helaili/jekyll-action@v2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     jekyll_src: "docs"
      #     jekyll_build_options:
      #       host: 127.0.0.1
      #       port: 4000
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: docs
          install-command: npm install
          build: npm run bulma-sass
          # start: JEKYLL_ENV=production jekyll serve --host 127.0.0.1 --port 4000
          wait-on: "http://127.0.0.1:4000"
